[package]
name = "profiling"
version = "0.1.0"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
edition = "2018"

[dependencies]
hyperjson = { path = ".." }

[dependencies.pyo3]
version = "0.5.0"

[profile.release]
debug = true
